version: '3.9'
services:
  web:
    build:
      context: .
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    environment:
      NODE_ENV: production
