version: '3.9'
services:
  web:
    image: node:18.17.0-alpine3.18 AS build
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    command: sh -c "cd /app; npm install; npm run start --host 0.0.0.0"  
